name: Release Build

on:
  push:
    tags:
      - v*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ github.ref_name }}" --draft --generate-notes

  build-firmware:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v4
      - name: Install arduino-cli
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew update
          brew install arduino-cli
      - name: Install Arduino core
        run: /home/linuxbrew/.linuxbrew/bin/arduino-cli core install "UCSB-IEEE:sam" --additional-urls "https://raw.githubusercontent.com/ucsbieee/ArduinoCore-SAM3A4C/master/package_TC-controller-3A4C_index.json"
      - name: Install Arduino libraries
        run: /home/linuxbrew/.linuxbrew/bin/arduino-cli lib install LiquidCrystal DueFlashStorage MIDIUSB
      - name: Build
        run: /home/linuxbrew/.linuxbrew/bin/arduino-cli compile --warnings all --clean -b "UCSB-IEEE:sam:TC_controller" --build-property "build.extra_flags=-D__SAM3A4C__ -DRELEASE_BUILD -mthumb {build.usb_flags}" -e Tesla_Coil_MIDI_Synth
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OUTNAME="Tesla_Coil_MIDI_Synth-${{ github.ref_name }}.bin"
          mv "Tesla_Coil_MIDI_Synth/build/UCSB-IEEE.sam.TC_controller/Tesla_Coil_MIDI_Synth.ino.bin" "$OUTNAME"
          gh release upload --clobber "${{ github.ref_name }}" "$OUTNAME"

  build-emulator-linux:
    if: false
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y portaudio19-dev libasound2-dev libfftw3-dev libsdl2-dev libsdl2-ttf-dev
      - name: Build
        run: make -C Emulator -j`nproc` RELEASE_BUILD=1
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OUTNAME="tcsynth-${{ github.ref_name }}-$(uname -sm | tr ' ' -)"
          mv Emulator/tcsynth "$OUTNAME"
          gh release upload --clobber "${{ github.ref_name }}" "$OUTNAME"

  build-emulator-macos:
    if: false
    runs-on: macos-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: |
          brew update
          brew install portaudio fftw sdl2 sdl2_ttf coreutils

          mkdir -p Emulator/static/x64 Emulator/static/arm64

          for lib in portaudio fftw SDL2 SDL2_ttf; do
            lib_lower=$(echo $lib | tr '[:upper:]' '[:lower:]')
            curl -sL https://formulae.brew.sh/api/formula/$lib_lower.json -o $lib_lower.json
            ARM_VERSION=$(jq -r '.bottle.stable.files | to_entries[] | .key' $lib_lower.json | grep -i '^arm64_' | fgrep -ivm1 linux)
            X64_VERSION=$(jq -r '.bottle.stable.files | to_entries[] | .key' $lib_lower.json | grep -Eivm1 '^arm64_|linux')

            echo Using $ARM_VERSION for arm64 $lib
            echo Using $X64_VERSION for x64 $lib

            jq -r ".bottle.stable.files.$ARM_VERSION.url" $lib_lower.json | xargs curl -sLH "Authorization: Bearer QQ==" | tar xf - -C Emulator/static/arm64 --strip-components=3 '*/lib'$lib'*.a'
            jq -r ".bottle.stable.files.$X64_VERSION.url" $lib_lower.json | xargs curl -sLH "Authorization: Bearer QQ==" | tar xf - -C Emulator/static/x64 --strip-components=3 '*/lib'$lib'*.a'
          done

          ls -lR Emulator/static
      - name: Build
        run: make -C Emulator -j`nproc` RELEASE_BUILD=1 tcsynth_universal
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OUTNAME="tcsynth-${{ github.ref_name }}-macOS-universal"
          mv Emulator/tcsynth_universal "$OUTNAME"
          gh release upload --clobber "${{ github.ref_name }}" "$OUTNAME"

  build-emulator-windows:
    if: false
    runs-on: windows-latest
    needs: create-release
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            make
            pkgconf
            patch
            coreutils
            mingw-w64-x86_64-portaudio
            mingw-w64-x86_64-fftw
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_ttf
            mingw-w64-x86_64-toolchain
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Fix symlinks
        run: |
          export MSYS=winsymlinks:nativestrict
          git config core.symlinks true
          git restore .
      - name: Build
        run: make -C Emulator -j`nproc` RELEASE_BUILD=1
      - name: Upload
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OUTNAME="tcsynth-${{ github.ref_name }}-Windows-$(uname -m).exe"
          mv Emulator/tcsynth.exe "$OUTNAME"
          gh release upload --clobber "${{ github.ref_name }}" "$OUTNAME"
